### 좌석 예약 요청 API

@concertId=1
@scheduleId=1

# Case 1: 정상 응답
POST {{host}}/api/concert/{{concertId}}/schedules/{{scheduleId}}/reservations
Content-Type: application/json
X-Reservation-Queue-Token: {{accessToken}}

{
  "seatNo": 13
}

###

# Case 2: 유효하지 않은 USER-TOKEN
POST {{host}}/api/concert/{{concertId}}/schedules/{{scheduleId}}/reservations
Content-Type: application/json
X-Reservation-Queue-Token: invalid-token

{
  "seatNo": 1
}

###

# Case 3: 유효하지 않은 concertId 또는 scheduleId
POST {{host}}/api/concert/999/schedules/888/reservations
Content-Type: application/json
X-Reservation-Queue-Token: {{accessToken}}

{
  "seatNo": 1
}

###

# Case 4: 유효하지 않은 좌석 번호 (50 이상의 수)
POST {{host}}/api/concert/{{concertId}}/schedules/{{scheduleId}}/reservations/
Content-Type: application/json
X-Reservation-Queue-Token: {{accessToken}}

{
  "reservationId": 51,
  "seatNo": 51
}
