### 결제 요청 API

# Case 1: 결제 성공
POST {{host}}/api/payment
Content-Type: application/json
X-Reservation-Queue-Token: Bearer valid-token-1

{
  "reservationId": 100
}

###

# Case 2: 결제 실패
POST {{host}}/api/payment
Content-Type: application/json
X-Reservation-Queue-Token: Bearer valid-token-2

{
  "reservationId": 100
}

###

# Case 3: 유효하지 않은 예약 ID
POST {{host}}/api/payment
Content-Type: application/json
X-Reservation-Queue-Token: Bearer valid-token-1

{
  "reservationId": 200
}

###

# Case 4: 유효하지 않은 USER-TOKEN
POST {{host}}/api/payment
Content-Type: application/json
X-Reservation-Queue-Token: invalid-token

{
  "reservationId": 100
}

###

# Case 5: 예약 ID 누락 또는 음수
POST {{host}}/api/payment
Content-Type: application/json
X-Reservation-Queue-Token: Bearer valid-token-1

{
  "reservationId": -1
}
